update workflows

diff --git a/.github/workflows/github-action.yaml b/.github/workflows/github-action.yaml
--- a/.github/workflows/github-action.yaml
+++ b/.github/workflows/github-action.yaml
@@ -71,7 +71,7 @@ jobs:
           cache-from: type=gha
           cache-to: type=gha,mode=max
           push: true
-          provenance: false
+          provenance: false  # Disable image index metadata
 
   redeploy_dev_service:
     name: Redeploy Dev Service
@@ -79,7 +79,14 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Redeploy Dev Service
-        run: curl -X POST ${{ secrets.PORTAINER_DEV_SERVICE_WEBHOOK }}
+        run: |
+          RESPONSE=$(curl -s -o response.txt -w "%{http_code}" -X POST ${{ secrets.PORTAINER_DEV_SERVICE_WEBHOOK }})
+          if [ "$RESPONSE" -ne 200 ]; then
+            echo "❌ Deployment failed! HTTP Response: $RESPONSE"
+            cat response.txt  # 오류 메시지 출력 (필요 시)
+            exit 1
+          fi
+          echo "✅ Deployment successful! HTTP Response: $RESPONSE"
 
   deploy_health_check:
     name: Check Application Status
